spring.application.name=echo
spring.datasource.url=jdbc:mysql://localhost:3306/echo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
echo.security.jwt.secret=kLl/Oxck2b0eL0I4AKPOI3So/YtflT6uUg8C4yulenK6JpRBtLdJHbYaEZD9t7o1l/4Ly3IYRgIFJ+D2F8BIlQ==
echo.security.jwt.expiration=3600000